//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kemel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kemel.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe coluna na coleção de colunas..
        /// </summary>
        public static string DontHaveColumnInColumnCollection {
            get {
                return ResourceManager.GetString("DontHaveColumnInColumnCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; não deve deve conter mais do que &quot;{1}&quot; caracteres..
        /// </summary>
        public static string FieldGreaterThanMaxLength {
            get {
                return ResourceManager.GetString("FieldGreaterThanMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; não deve deve estar em branco pois é obrigatório..
        /// </summary>
        public static string FieldNotEmpty {
            get {
                return ResourceManager.GetString("FieldNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de coluna inválida..
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operador inválido para esta operação.
        /// </summary>
        public static string InvalidOperator {
            get {
                return ResourceManager.GetString("InvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção inválida..
        /// </summary>
        public static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método é exclusivo para entidades..
        /// </summary>
        public static string MethodIsExclusiveToEntity {
            get {
                return ResourceManager.GetString("MethodIsExclusiveToEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credencial é necessária..
        /// </summary>
        public static string NullCredentialException {
            get {
                return ResourceManager.GetString("NullCredentialException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orm Starter com a credencial configurada é necessário..
        /// </summary>
        public static string NullOrmStartesException {
            get {
                return ResourceManager.GetString("NullOrmStartesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chave primária não existe ou esta nula.
        /// </summary>
        public static string PrimaryKeyIsNull {
            get {
                return ResourceManager.GetString("PrimaryKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propriedade {0} não pode estar nula..
        /// </summary>
        public static string PropertyDoesNotNull {
            get {
                return ResourceManager.GetString("PropertyDoesNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma operação de tabela antes..
        /// </summary>
        public static string SetTableOperationBefore {
            get {
                return ResourceManager.GetString("SetTableOperationBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela não encontrada na query..
        /// </summary>
        public static string TableDoesNotExistInQuery {
            get {
                return ResourceManager.GetString("TableDoesNotExistInQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Tipo não é uma extensão de entidade..
        /// </summary>
        public static string TypeDoesntExtendsFromEntity {
            get {
                return ResourceManager.GetString("TypeDoesntExtendsFromEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo não esperado..
        /// </summary>
        public static string TypeNotExpected {
            get {
                return ResourceManager.GetString("TypeNotExpected", resourceCulture);
            }
        }
    }
}
