//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.4952
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kemel.Orm.Teste.Bll.Entity {
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Text;
    using Kemel.Orm;
    using Kemel.Orm.Base;
    using Kemel.Orm.Schema;
    using Kemel.Orm.Entity.Attributes;


    public partial class T_TIPO_EMPRESA_Entity {

        public class Definition {

            public const string TABLE_NAME = "T_TIPO_EMPRESA";

            public const string CODIGO = "CODIGO";

            public const string DESCRICAO = "DESCRICAO";
        }
    }
}
