//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.4952
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kemel.Orm.Teste.Bll.Entity {
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Text;
    using Kemel.Orm;
    using Kemel.Orm.Base;
    using Kemel.Orm.Schema;
    using Kemel.Orm.Entity.Attributes;


    [TableSchemaType(global::Kemel.Orm.Entity.Attributes.SchemaType.Table)]
    public partial class T_PESSOA_Entity : Kemel.Orm.Entity.EntityBase {

        private System.Nullable<int> f_codigo;

        private string f_nome;

        private System.Nullable<bool> f_inativo;

        #region CODIGO
        /// <summary>
        /// <para>É chave primária.</para>
        /// É auto-incrementável.
        /// Não permite nulo.
        /// </summary>
        [Identity(true)]
        [PrimaryKey(true)]
        [AllowNull(false)]
        public virtual System.Nullable<int> CODIGO {
            get {
                return this.f_codigo;
            }
            set {
                this.f_codigo = value;
            }
        }
        #endregion

        #region NOME
        /// <summary>
        /// Não permite nulo.
        /// </summary>
        [Identity(false)]
        [PrimaryKey(false)]
        [AllowNull(false)]
        [MaxLength(10)]
        public virtual string NOME {
            get {
                return this.f_nome;
            }
            set {
                this.f_nome = value;
            }
        }
        #endregion

        #region INATIVO
        /// <summary>
        /// Não permite nulo.
        /// </summary>
        [Identity(false)]
        [PrimaryKey(false)]
        [AllowNull(false)]
        [LogicalExclusionColumn()]
        public virtual System.Nullable<bool> INATIVO {
            get {
                return this.f_inativo;
            }
            set {
                this.f_inativo = value;
            }
        }
        #endregion
    }
}
