//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.4952
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kemel.Orm.Teste.Bll.Dal {
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Text;
    using Kemel.Orm;
    using Kemel.Orm.Base;
    using Kemel.Orm.Schema;
    using Kemel.Orm.Data;
    using Kemel.Orm.Providers;
    using Kemel.Orm.Teste.Bll.Entity;


    public class T_EMPRESA_Dal : Kemel.Orm.Base.Dal<T_EMPRESA_Entity> {
    }
}
