//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.4952
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kemel.Orm.Teste.Bll.Dal {
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Text;
    using Kemel.Orm;
    using Kemel.Orm.Base;
    using Kemel.Orm.Schema;
    using Kemel.Orm.Data;
    using Kemel.Orm.Providers;
    using Kemel.Orm.Teste.Bll.Entity;
    using Kemel.Orm.NQuery.Storage;


    public class T_PESSOA_Dal : Kemel.Orm.Base.Dal<T_PESSOA_Entity> {

        internal DataTable QuerySimples()
        {
            Query qry = this.Select().From<T_PESSOA_Entity>().WithNoLock()
                    .Column(T_PESSOA_Entity.Schema.NOME).As("Pessoa").As("P").EndTable()
                    .Where(T_PESSOA_Entity.Schema.NOME).Equal("Diego");

            return qry.Execute().DataTable();
        }

        internal List<T_EMPRESA_Entity> ExtendedProperties()
        {
            return this.Select().From<T_EMPRESA_Entity>().As("E").AllColumns()
                    .Join<T_TIPO_EMPRESA_Entity>().As("TE").Column(T_TIPO_EMPRESA_Entity.Schema.DESCRICAO).As("TipoEmpresa").AsJoin()
                        .On(T_TIPO_EMPRESA_Entity.Schema.CODIGO).Equal(T_EMPRESA_Entity.Schema.TIPO_EMPRESA).AsInner()
                    .Execute().List<T_EMPRESA_Entity>(true);

        }

        internal DataTable DataTableJoin()
        {
            return this.Select().From<T_EMPRESA_Entity>().As("E").AllColumns()
                    .Join<T_TIPO_EMPRESA_Entity>().As("TE").Column(T_TIPO_EMPRESA_Entity.Schema.DESCRICAO).As("TipoEmpresa").AsJoin()
                        .On(T_TIPO_EMPRESA_Entity.Schema.CODIGO).Equal(T_EMPRESA_Entity.Schema.TIPO_EMPRESA).AsInner()
                    .OrderBy(T_EMPRESA_Entity.Schema.NOME).Asc()
                    .Execute().DataTable();
        }

        internal DataTable QueryComRepeticaoDeTabelaNoJoin()
        {
            Query qry = this.Select().From<T_EMPRESA_Entity>().As("E").AllColumns();
            qry.Join<T_TIPO_EMPRESA_Entity>().As("TE1").Column(T_TIPO_EMPRESA_Entity.Schema.DESCRICAO).As("TipoEmpresa01").AsJoin()
                .On(T_TIPO_EMPRESA_Entity.Schema.CODIGO).Equal(T_EMPRESA_Entity.Schema.TIPO_EMPRESA)
                .And(T_TIPO_EMPRESA_Entity.Schema.CODIGO).GreaterThanOrEqual(10)
                .AsInner();
            qry.Join<T_TIPO_EMPRESA_Entity>().As("TE2").Column(T_TIPO_EMPRESA_Entity.Schema.DESCRICAO).As("TipoEmpresa02").AsJoin()
                .On(T_TIPO_EMPRESA_Entity.Schema.CODIGO).Equal(T_EMPRESA_Entity.Schema.TIPO_EMPRESA)
                .And(T_TIPO_EMPRESA_Entity.Schema.CODIGO).LessThan(10)
                .AsInner();
            qry.OrderBy(T_EMPRESA_Entity.Schema.NOME).Asc();
            OrmCommand cmd = qry.Execute(this.Transaction).CreateCommand();
            return cmd.ExecuteDataTable();
        }

        internal DataTable QuerySimplesComLimit()
        {
            Query qry = this.Select().From<T_PESSOA_Entity>().WithNoLock()
                    .AllColumns()
                    .Limit(5, 10);

            qry.Count().As("Qtd");
            qry.GroupBy(T_PESSOA_Entity.Schema.CODIGO, T_PESSOA_Entity.Schema.NOME, T_PESSOA_Entity.Schema.INATIVO);

            return qry.Execute().DataTable();
        }
    }
}
