//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kemel.Tools.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kemel.Tools.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Senha de confirmação não confere..
        /// </summary>
        public static string ConfirmPasswordDontMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordDontMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Senha atual é igual a nova senha..
        /// </summary>
        public static string CurrentPasswordIsEqualNewPassword {
            get {
                return ResourceManager.GetString("CurrentPasswordIsEqualNewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desativação de registro realizada com sucesso..
        /// </summary>
        public static string InactivationCompleted {
            get {
                return ResourceManager.GetString("InactivationCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não foi possível desativar o registro..
        /// </summary>
        public static string InactivationError {
            get {
                return ResourceManager.GetString("InactivationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preenchimento incorreto do campo {0}..
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuário e/ou senha inválido(s)..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Senha inválida..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuário não autorizado..
        /// </summary>
        public static string NotAuthorizedUser {
            get {
                return ResourceManager.GetString("NotAuthorizedUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} já adicionado(a)..
        /// </summary>
        public static string ObjectAlreadyAdded {
            get {
                return ResourceManager.GetString("ObjectAlreadyAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} já existente..
        /// </summary>
        public static string ObjectAlreadyExists {
            get {
                return ResourceManager.GetString("ObjectAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} não encontrado(a)..
        /// </summary>
        public static string ObjectNotFound {
            get {
                return ResourceManager.GetString("ObjectNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O preenchimento do campo {0} é obrigatório..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso..
        /// </summary>
        public static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Informe pelo menos um dos filtros para a consulta..
        /// </summary>
        public static string SupplyAtLeastOneFilter {
            get {
                return ResourceManager.GetString("SupplyAtLeastOneFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro não esperado durante a operação..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
