//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.4952
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kemel.Orm.Teste.Bll.Business {
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Text;
    using Kemel.Orm;
    using Kemel.Orm.Base;
    using Kemel.Orm.Schema;
    using Kemel.Orm.Data;
    using Kemel.Orm.Providers;
    using Kemel.Orm.Teste.Bll.Entity;
    using Kemel.Orm.Teste.Bll.Dal;


    public class BusinessPessoa : Kemel.Orm.Base.Business<T_PESSOA_Entity, T_PESSOA_Dal> {

        public DataTable QuerySimples()
        {
            return this.Dal.QuerySimples();
        }

        public List<T_EMPRESA_Entity> ExtendedProperties()
        {
            return this.Dal.ExtendedProperties();
        }

        public DataTable DataTableJoin()
        {
            return this.Dal.DataTableJoin();
        }

        public DataTable QueryComRepeticaoDeTabelaNoJoin()
        {
            return this.Dal.QueryComRepeticaoDeTabelaNoJoin();
        }

        public DataTable QuerySimplesComLimit()
        {
            return this.Dal.QuerySimplesComLimit();
        }
    }
}
